apiVersion: apps/v1
kind: Deployment
metadata:
  name: gronos
  namespace: setup
  labels:
    app: gronos
    environment: production
    version: v2.8.4
spec:
  selector:
    matchLabels:
      app: gronos
      environment: production
      version: v2.8.4
  template:
    metadata:
      labels:
        app: gronos
        environment: production
        version: v2.8.4
    spec:
      containers:
        - name: gronos
          image: gcr.io/evmd-sfa-prd/evmd-gronos:latest
          command: ["/gronos"]
          resources:
            limits:
              memory: "50Mi"
              cpu: "100m"
            requests:
              memory: "10Mi"
              cpu: "10m"
          ports:
            - containerPort: 80
          env:
            - name: GRONOS_DATABASE_DSN
              valueFrom:
                secretKeyRef:
                  name: gronos-config
                  key: dsn
            - name: FAKTORY_URL
              valueFrom:
                secretKeyRef:
                  name: jobs-config
                  key: faktory_url
            - name: GRONOS_DATABASE_MAXOPENCONNS
              value: "5"
            - name: GRONOS_DATABASE_MAXIDLECONNS
              value: "1"
            - name: GRONOS_DATABASE_MAXLIFETIME
              value: "3"
            - name: GRONOS_SCHEDULE
              value: "@every 5s"
            - name: STACKS
              value: "setup"
